create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 2 and 10),
  score bigint not null check (score >= 0),
  stage integer not null check (stage between 1 and 3),
  loop integer not null check (loop between 1 and 99),
  game_duration integer not null default 0,
  game_version text not null default 'web',
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_score_idx
  on public.leaderboard (score desc, created_at asc);

alter table public.leaderboard enable row level security;

-- No public insert/select policies are created on purpose. The browser never
-- receives database credentials; only the Netlify Function uses the Supabase
-- service role key and exposes the narrow GET/POST leaderboard API.
